<?php
/**
 * Copyright © 2015 vendorcommerce. All rights reserved.
 */
?>

<form class="form contact"
      action="<?= /* @noEscape */ $block->getUrl('servicemodel/grid/save') ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'
      enctype='multipart/form-data'>
    <fieldset class="fieldset">
        <div class="field note">
            <label class="label" for="note"><span>
                    <?= $block->escapeHtml(__('Please upload the document for the details descritipion. 
                    We will get back to you in 5-10 days.')) ?></span></label>
        </div>
        <div class="field customer_file required">
            <label class="label" for="document"><span><?= $block->escapeHtml(__('Document')) ?></span></label>

                <input type="hidden" name="customer_id" id="customer_id" value="
                <?= /* @noEscape */ $block->getCustomerId()?>"/>
                <input type="hidden" name="insert_date" id="insert_date" value="
                <?= /* @noEscape */ $block->getCurrentDate()?>"/>
                <input type="file" name="customer_file" id="customer_file" title="
                <?= /* @noEscape */ $block->escapeHtmlAttr(__('Customer File')) ?>"
                       value="" data-validate="{required:true}"/>

        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
